# This is a basic workflow to help you get started with Actions 

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# Define name of script
env:
  scriptname: m-scriptname.py

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: main
 
      - name: Checkout destination rep
        uses: actions/checkout@v2
        with:
          repository: cchowthi/scripts
          token: ${{ secrets.cchowthi_pat }}
          path: scripts
          
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          
      - name: Commit to destination repo
        run: |
          cd scripts
          cp ../main/${{ env.scriptname }} ./
          git config --global user.name "${{ secrets.my_name }}"
          git config --global user.email  "${{ secrets.my_email }}"
          git fetch
          git checkout main
          git add ${{ env.scriptname }}
          git commit -m "Automatic update of scripts"
          git push
